name: my_workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        run: exit 0
  main:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy app
        run: |
          echo "this is main branch"
  non_main:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/release/1.0.0'
    steps:
      - name: Deploy app
        run: |
          echo "this is not main branch"
