name: Create our Weekly Meeting notes issue
on:
  # schedule:
  #   - cron: '51 5 * * *'
  workflow_dispatch:
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/meeting-notes.md